### ISSUE TITLE
what is the upper channel for

### ISSUE THREAD

**Issue by dlarue** [rbgo/AtomStack-M50-AirAssist#1]
Is that upper channel and subsequent outside loop into the cone section an effort to try and cool the lens before pressurizing the cone?

**Comment by rbgo** [comment]
Yes true. And it works.
The area with the threaded brass lens holder is not cooled much and already had a cracked lens.
They send me a new laser unit and then the eyes for the screws did not fit anymore; they did a revision.
Did not updated the CAD file but just saw them away and fitted it by screwing it on the brass while firmly pushing.
THe air IN is for a 4x2mm PTFE tube through the unit up through the acrylic lid at the top.
